name: Build

on:
  push:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout action
  #        uses: actions/checkout@v4
  #
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Repository Variables
        run: |
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Path: ${{ github.event_path }}"

      - name: Debug envirınment variables
        run: |
          echo "REGISTRY: ${{ env.REGISTRY }}"
          echo "REPO_OWNER: ${{ env.REPO_OWNER }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "GH_TOKEN: ${{ env.GH_TOKEN }}"

      - name: Debug Secret Value
        run: |
          echo "GH_TOKEN: ${{ secrets.GH_TOKEN }}"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

#
#      - name: Extract image metadata
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/petShop:latest
#
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: ${{ env.REPO_OWNER }}/petshop:latest
#          labels: ${{ steps.meta.outputs.labels }}
#          secrets: |
#            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
